---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenav
  namespace: kubenav
  labels:
    app.kubernetes.io/instance: kubenav
    app.kubernetes.io/name: kubenav
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: kubenav
      app.kubernetes.io/name: kubenav
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: kubenav
        app.kubernetes.io/name: kubenav
    spec:
      serviceAccountName: kubenav
      containers:
        - name: kubenav
          image: kubenav/kubenav:3.3.0
          imagePullPolicy: IfNotPresent
          args:
             - --kubeconfig=/kubenav/kubeconfig/kubeconfig
          volumeMounts:
            - name: kubeconfig
              mountPath: '/kubenav/kubeconfig'
              readOnly: true
          ports:
            - name: http
              containerPort: 14122
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
          resources:
            limits:
              cpu: 400m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: kubeconfig
          secret:
            secretName: kubeconfig
